import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/context/AuthProvider";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Vehicle Booking",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialised`}
        
        suppressHydrationWarning={true}
      >
        <AuthProvider>
<Header></Header>
          <div className="min-h-screen px-4 md:px-8 lg:px-16 py-6 max-w-7xl mx-auto">
            {children}
          </div>
         
        </AuthProvider>
      </body>
    </html>
  );
}
